### PR TITLE
uncontrolled data used in path expression

### PR DESCRIPTION
**Pull request by sand-hya**
This code change addresses multiple issue of "uncontrolled data used in path expression"

### CODE REVIEW

**Comment by Anjana2310** [comment]
@sand-hya Kindly confirm if testing is done for the same.

**Comment by sand-hya** [comment]
@Anjana2310 : Yes, we have tested the functionality and it is working as expected. We have reviewed and did the necessary changes. Kindly review.

**Review by ravishanigarapu — COMMENTED** [review]
Please attach test document or screenshorts

**Review by ravishanigarapu — APPROVED** [review]
looks ok to me

**Review by devikasuresh20 — APPROVED** [review]

**Pull request merged**
